// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfB6SVv9PfcJ2L7ktPKlT_WHQf1td_CSk',
    appId: '1:286586753314:web:0bfe08e70001b97820957b',
    messagingSenderId: '286586753314',
    projectId: 'slotifyapp',
    authDomain: 'slotifyapp.firebaseapp.com',
    storageBucket: 'slotifyapp.appspot.com',
    measurementId: 'G-95J9EK7FGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCybk8jpVtWBU3EkK41Rql66HpQSVWYmc0',
    appId: '1:286586753314:android:bc6c6640d74b9bbd20957b',
    messagingSenderId: '286586753314',
    projectId: 'slotifyapp',
    storageBucket: 'slotifyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Iv5we0dYsL5Z6ATw8FqTD5GMEJEnQHE',
    appId: '1:286586753314:ios:c2b986cfa0203a0620957b',
    messagingSenderId: '286586753314',
    projectId: 'slotifyapp',
    storageBucket: 'slotifyapp.appspot.com',
    iosBundleId: 'in.kishanpanchal.slotifyapp',
  );
}